Repository sandeepdwivedi18/Hactoberfest2024, pull requests merged in 2024-10, with the labels that each got.

#1 Basic_Portfolio.html
  Basic_Portfolio.html
Labels: hacktoberfest2024

#7 Created readme.md
  readme.md
Labels: documentation

#6 Added a poker game using python
  Poker_game/README.md
  Poker_game/poker.py
Labels: hacktoberfest2024

#9 Celsius_Fahrenheit_Calculator.py
  Celsius_Fahrenheit_Calculator.py
Labels: hacktoberfest2024, hacktoberfest-accepted

#12 added two sum problem in c++
  two sum.c++
Labels: hacktoberfest2024, hacktoberfest-accepted
